### ISSUE TITLE
distrowatch.com timeout when using socks5 proxy

### ISSUE THREAD

**Issue by git70** [mullvad/browser-extension#180]
Strange behavior, but I can't find any other explanation:
An attempt to enter [distrowatch.com](https://distrowatch.com) ends in failure (timeout). 
Just disconnect the proxy and it loads correctly. 
Can you reproduce this behavior in yourself?

**Comment by ruihildt** [comment]
I can confirm and reproduce, the reason is that our socks proxy forces use of IPv6 when announced as available by the website.

Unfortunately, distrowatch.com has seemingly misconfigured their IPv6 implementation, which results in a timeout when trying to load the website.

I suggest contacting the website to get their IPv6 implementation fixed.
