### ISSUE TITLE
Disabling Proxy Does not Work

### ISSUE THREAD

**Issue by tinyvoice** [mullvad/browser-extension#197]
Under the Proxy tab, there is a "Proxy for all websites" toggle. Expected behavior is that when the this toggle is disabled, the browser stops proxying traffic through the Mullvad SOCKS proxy. Instead, when I disable this toggle and the DNS toggle, it falls back to some default or random location and proxies the traffic through that. For instance, as shown in the screenshots, the proxy was set to an Oslo, Norway, server. When I disabled the proxy toggle, it did not turn off the SOCKS proxy. It started routing through an Atlanta, US, server. I do not know how or why this server was selected, as I did not select it, and it is not the server selected on the VPN client. Also, setting the specific site to Never Proxy also has the same issue.

This was tested on Firefox and the Mullvad Browser with the same results. When the toggle is set to disable, it should stop routing traffic completely.

![1-enabled](https://github.com/mullvad/browser-extension/assets/117961980/2b526589-3d52-47e9-bbdd-88a36b404976)
![2-disabled](https://github.com/mullvad/browser-extension/assets/117961980/1589373a-a659-43f0-8cea-81981b20565d)
![3-disabled](https://github.com/mullvad/browser-extension/assets/117961980/fdb0a3cb-945d-43d9-9e49-640366809647)

**Comment by ruihildt** [comment]
Hi @tinyvoice , does this always connect to the Atlanta server?
If so, can you check in `Menu` > `Settings` > `General` > `Network Settings` > `Settings` that there's no custom proxy in use?

**Comment by ruihildt** [comment]
There's something wrong here, because your last screenshot should show `Use system proxy settings` and no mention of `Mullvad Browser Extension controls how Mullvad Browser connects to the internet`.

It may be that I haven't managed to cover correctly the migration from the old proxy settings to the new one, and I apologize for that.

If that's acceptable for you, can you try to reset the proxy settings completely and see if that fixes it for you?
This will delete your current proxy settings, and you will be connecting to the internet through you current system connection.

- go to `about:debugging#/runtime/this-firefox`
- scroll until `Mullvad Browser Extension` and click on `Inspect`
- the `Developer Tools` window opens
- click on the `Storage` tab
- on the left menu, click on `Extension Storage`
- under `Extension Storage`, another line expands starting with `moz-extension://...`
- right click on it
- click `Delete all`

**Comment by ruihildt** [comment]
I could reproduced it.

Before 0.9.0, the extension would set the proxy through the browser `Connection Settings`.
The new proxy implementation will take precedence over the proxy set in `Connection Settings`, but will not remove it. So when you disable the proxy in the new implementation, the proxy in `Connection Settings` is still there and will be active.

If someone faces the same error at some point in the future, uninstalling and reinstalling the extension will indeed reset its configuration.
