### ISSUE TITLE
Recommend multi-account containers

### ISSUE THREAD

**Issue by ruihildt** [mullvad/browser-extension#23]
Containers are well integrated in Firefox and could be useful to improve privacy.

We could look into recommending using them.

See: https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/

**Comment by ph00lt0** [comment]
Containers are build in to Firefox. You do not need an extension for obtaining isolation If you use dFPI (https://blog.mozilla.org/security/2021/02/23/total-cookie-protection/) you already have everything this extension offers. Adding extensions into your browser is not recommendable.

**Comment by felschr** [comment]
I'm quite interested in this topic, but I don't fully understand these options.

As far as I see, Mullvad Browser currently doesn't currently use Total Cookie Protection (`network.cookie.cookieBehavior` & `network.cookie.cookieBehavior.pbmode` are set to `1` instead of `5`).
Are there any downsides of enabling Total Cookie Protection in contrast to Mullvad Browser's current default setting of blocking all third-party cookies?

Mozilla has an article about Total Cookie Protection & Multi-Account Containers:
https://blog.mozilla.org/en/products/firefox/extensions-addons/how-firefoxs-total-cookie-protection-and-container-extensions-work-together/
To me it sounds like Multi-Account Containers don't have any general privacy benefits over Total Cookie Protection like @ph00lt0 already said *unless* you want to separate sessions on the same domain, which is a likely a rarer case.

Is it safe to enable Total Cookie Protection (`network.cookie.cookieBehavior = 5`) right now as a user on Mullvad Browser or is that fingerprintable somehow?

If I've interpreted this all right, I'd say Multi-Account Containers definitely shouldn't be preinstalled and a recommended should be limited with an explanation about how it differs from Total Cookie Protection (once adopted).

**Comment by ruihildt** [comment]
This issue was opened before Mullvad Browser was a thing. :)

@felschr I created an issue based on your comment as this is more of a Mullvad Browser question.

**Comment by felschr** [comment]
Oh, I didn't even realise I wasn't in Mullvad Browser's issues 😅.

**Comment by ruihildt** [comment]
As there are no tangible privacy benefits, and because containers are not supported in Mullvad Browser, I'll close this issue. 

If someone feels strongly otherwise, please feel free to comment.
